# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Suve < Formula
  desc "Git-like CLI for AWS Parameter Store and Secrets Manager"
  homepage "https://github.com/mpyw/suve"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mpyw/suve/releases/download/v0.1.1/suve_0.1.1_darwin_amd64.tar.gz"
      sha256 "53ef8dffc576d9ae458336648fd4f591c332dd6ec7e1de643b7b265b33477bd9"

      def install
        bin.install "suve"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mpyw/suve/releases/download/v0.1.1/suve_0.1.1_darwin_arm64.tar.gz"
      sha256 "e52b00f293077a8cb2c13e6eb9fa8405f32392a5aa872a8b52712307ac07f613"

      def install
        bin.install "suve"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mpyw/suve/releases/download/v0.1.1/suve_0.1.1_linux_amd64.tar.gz"
      sha256 "ccf7aeefa6490fcab8c16f83cba7717783e9c417df63f69ac8b05152abd7161c"
      def install
        bin.install "suve"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mpyw/suve/releases/download/v0.1.1/suve_0.1.1_linux_arm64.tar.gz"
      sha256 "505da401a9ffe401548949ef40ff681baecd0f619199700adf705143ac1f9ab5"
      def install
        bin.install "suve"
      end
    end
  end

  test do
    system "#{bin}/suve", "--version"
  end
end
