# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Suve < Formula
  desc "Git-like CLI for AWS Parameter Store and Secrets Manager"
  homepage "https://github.com/mpyw/suve"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mpyw/suve/releases/download/v0.1.0/suve_0.1.0_darwin_amd64.tar.gz"
      sha256 "f72c90f82a3aeb22b050dbc15daf3119212a852ee25e63902934c7bc9f44c531"

      def install
        bin.install "suve"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mpyw/suve/releases/download/v0.1.0/suve_0.1.0_darwin_arm64.tar.gz"
      sha256 "97f9a3388676253aa3401ef390befe04fbf5fe7e49eb802fca1c80826ed121da"

      def install
        bin.install "suve"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mpyw/suve/releases/download/v0.1.0/suve_0.1.0_linux_amd64.tar.gz"
      sha256 "a6114c53a6001fb05e360967822b702e0b9d084bd96710dbe800fa6a7054b4fe"
      def install
        bin.install "suve"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mpyw/suve/releases/download/v0.1.0/suve_0.1.0_linux_arm64.tar.gz"
      sha256 "1463aa3003ddb1504b48cd9c11a78137d155078c387c30bc78c98a7d441d2072"
      def install
        bin.install "suve"
      end
    end
  end

  test do
    system "#{bin}/suve", "--version"
  end
end
